### ISSUE TITLE
[PAL] Ice Age 2 The Meltdown BlockOnTime error

### ISSUE THREAD

**Issue by PatrickvL** [Cxbx-Reloaded/game-compatibility#109]
_From @rexcaptain501 on May 4, 2017 0:24_

Tested on Cxbx-Reloaded build 36f9e17, May 3 2017

In Hardware mode, the game will eventually crash with a blueshogun error (* D3D::BlockOnTime not implemented). Software mode has an immediate crash with no audio or video.

Hardware mode crash: ![Photo 1](https://cloud.githubusercontent.com/assets/10300935/25686686/51ba6830-30c4-11e7-9f6e-258cbe930616.PNG)

Ice Age 2 The Meltdown (default.xbe) .xbe info dump: [Xbe.txt](https://github.com/Cxbx-Reloaded/Cxbx-Reloaded/files/974990/Xbe.txt)

Hardware mode Kernel Debug file: [KrnlDebug.txt](https://github.com/Cxbx-Reloaded/Cxbx-Reloaded/files/974994/KrnlDebug.txt)

Settings used:

Display Adapter: NVIDIA GeForce GTX 1060 6GB
Direct3D Device: Direct3D HAL (Hardware)
Video Resolution: Automatic (Default)

_Copied from original issue: Cxbx-Reloaded/Cxbx-Reloaded#431_

**Comment by PatrickvL** [comment]
_From @rexcaptain501 on May 4, 2017 0:24_

@blueshogun96 (* D3D::BlockOnTime not implemented)

**Comment by PatrickvL** [comment]
_From @blueshogun96 on May 4, 2017 2:24_

One of us REEEEEEEEALLY needs to get in there and fix that.  Btw, it won't matter what your settings are in this case because it's a missing or broken signature.  I noticed Luke comments some of these out, but I don't know why (uncommenting two of them fixed the 4920 dashboard for me).  But since I don't have this game personally, I can only assume it's similar to the issue with Turok now.  So I'll fire up turok later on and see what it is because this is coming up far too often.

Shogun.

**Comment by BenNottelling** [comment]
I know Turok had the same error and has been fixed now, could @rexcaptian501 retest this?

**Comment by rexcaptain501** [comment]
Sure. Tested with Cxbx-Reloaded build c8c4f81e (Aug 20 2017).

![1](https://user-images.githubusercontent.com/10300935/29591710-4221fc80-87f4-11e7-8727-fef1c9f28dd6.PNG)

Still getting that D3D::BlockOnTime not implemented error.

Kernel Debug file: [KrnlDebug.txt](https://github.com/Cxbx-Reloaded/game-compatibility/files/1243684/KrnlDebug.txt)

**Comment by gandalfthewhite19890404** [comment]
### Description
ingame, but with broken graphics. Menus are working (at least you can see something). Sound is not works.

### Status
**Previous behavior:**
crashes
**Current behavior:**
in-game but not playable due broken graphics.

### Screenshots
![image](https://user-images.githubusercontent.com/24764335/82114334-3e428e00-976d-11ea-8c96-1d9d1b5dfd2d.png)


### Additional Information
All hacks are disabled.
Used build 935fab7
